"""
Generic model recovery — builds the confusion matrix and inversion matrix
for a set of candidate models.

For each generating model:
  - simulate n_sims datasets from sensible parameters
  - fit every candidate model
  - record which candidate "won" by the supplied IC (lower is better, e.g., AIC/BIC/NLL+penalty)

Then:
  - confusion[gen, fit] = P(best-fit model = fit | data generated by gen)
  - inversion[gen, fit] = P(generating model = gen | best-fit model = fit)

Usage:

    models = {
        "rw":  {"simulate": sim_rw,  "fit": fit_rw,  "k": 2},
        "rwf": {"simulate": sim_rwf, "fit": fit_rwf, "k": 3},
    }
    cm, im = run_model_recovery(models, n_sims=50, n_trials=200, ic="aic")
    print_recovery_matrices(cm, im)
"""

from __future__ import annotations
import numpy as np
import pandas as pd
from typing import Callable


def run_model_recovery(
    models: dict[str, dict],
    n_sims: int = 50,
    n_trials: int = 200,
    ic: str = "aic",
    seed: int | None = 42,
    extra_sim_kwargs_per_model: dict[str, dict] | None = None,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Build confusion + inversion matrices for a set of candidate models.

    Each entry of ``models`` is a dict with:
      - "simulate": callable(params_dict, n_trials=...) -> data dict
      - "fit": callable(data) -> dict with at minimum "nll" and "k" keys
      - "param_sampler": callable(rng) -> params_dict, OR
        "param_ranges": dict[str, (low, high)] for uniform sampling
      - "k": int (number of free params; can also live in fit() output)

    Parameters
    ----------
    ic : {"aic", "bic", "nll"}
        Information criterion to compare candidates by.
    """
    rng = np.random.default_rng(seed)
    extra_sim_kwargs_per_model = extra_sim_kwargs_per_model or {}
    model_names = list(models.keys())

    # Per-generating-model loop
    winner_counts = pd.DataFrame(
        0, index=model_names, columns=model_names, dtype=int
    )
    winner_counts.index.name = "generating_model"
    winner_counts.columns.name = "best_fit_model"

    for gen_name in model_names:
        gen_spec = models[gen_name]
        sim_fn = gen_spec["simulate"]
        sampler = gen_spec.get("param_sampler")
        ranges = gen_spec.get("param_ranges")
        if sampler is None and ranges is None:
            raise ValueError(f"{gen_name} needs param_sampler or param_ranges")

        for s in range(n_sims):
            if sampler is not None:
                truth = sampler(rng)
            else:
                truth = {p: float(rng.uniform(lo, hi))
                         for p, (lo, hi) in ranges.items()}

            extra = extra_sim_kwargs_per_model.get(gen_name, {})
            data = sim_fn(truth, n_trials=n_trials, **extra)

            scores = {}
            for cand_name in model_names:
                cand_spec = models[cand_name]
                try:
                    fit_out = cand_spec["fit"](data)
                    nll = float(fit_out["nll"])
                    k = int(fit_out.get("k", cand_spec.get("k", 0)))
                    if ic == "aic":
                        score = 2 * nll + 2 * k
                    elif ic == "bic":
                        score = 2 * nll + k * np.log(n_trials)
                    elif ic == "nll":
                        score = nll
                    else:
                        raise ValueError(f"Unknown IC: {ic}")
                    scores[cand_name] = score
                except Exception:
                    scores[cand_name] = np.inf

            winner = min(scores, key=scores.get)
            winner_counts.loc[gen_name, winner] += 1

    # Confusion: rows sum to 1 (P(winner | generator))
    confusion = winner_counts.div(winner_counts.sum(axis=1), axis=0)
    # Inversion: cols sum to 1 (P(generator | winner))
    col_totals = winner_counts.sum(axis=0).replace(0, np.nan)
    inversion = winner_counts.div(col_totals, axis=1)

    confusion.attrs["counts"] = winner_counts
    inversion.attrs["counts"] = winner_counts
    return confusion, inversion


def print_recovery_matrices(
    confusion: pd.DataFrame, inversion: pd.DataFrame
) -> None:
    print("Confusion matrix — P(best-fit model = column | data generated by row)")
    print("Goal: identity matrix. Off-diagonals reveal which models the design confuses.")
    print(confusion.round(3))
    print()
    print("Inversion matrix — P(generating model = row | best-fit model = column)")
    print("Goal: identity matrix. Tells you which 'wins' you can trust.")
    print(inversion.round(3))

    diag = np.diag(confusion.values).mean()
    print()
    print(f"Mean diagonal of confusion matrix: {diag:.3f}")
    if diag > 0.9:
        print("  → excellent model recovery overall")
    elif diag > 0.7:
        print("  → reasonable; check off-diagonals for specific confusions")
    elif diag > 0.5:
        print("  → marginal; some models cannot be reliably distinguished by this design")
    else:
        print("  → poor; design likely under-discriminates the candidate set")


if __name__ == "__main__":
    # Self-test: distinguish Rescorla-Wagner (single α) from
    # dual-rate RL (separate α for positive vs negative RPE).
    from scipy.optimize import minimize

    def sim_rw(params, n_trials=200, reward_probs=(0.7, 0.3), seed=None):
        rng = np.random.default_rng(seed)
        a, b = params["alpha"], params["beta"]
        Q = np.zeros(2)
        ch, rw = [], []
        for _ in range(n_trials):
            p = np.exp(b * Q - np.max(b * Q)); p /= p.sum()
            c = int(rng.choice(2, p=p))
            r = float(rng.random() < reward_probs[c])
            Q[c] += a * (r - Q[c])
            ch.append(c); rw.append(r)
        return {"choices": np.array(ch), "rewards": np.array(rw)}

    def sim_dual(params, n_trials=200, reward_probs=(0.7, 0.3), seed=None):
        rng = np.random.default_rng(seed)
        ap, an, b = params["alpha_p"], params["alpha_n"], params["beta"]
        Q = np.zeros(2)
        ch, rw = [], []
        for _ in range(n_trials):
            p = np.exp(b * Q - np.max(b * Q)); p /= p.sum()
            c = int(rng.choice(2, p=p))
            r = float(rng.random() < reward_probs[c])
            pe = r - Q[c]
            a = ap if pe > 0 else an
            Q[c] += a * pe
            ch.append(c); rw.append(r)
        return {"choices": np.array(ch), "rewards": np.array(rw)}

    def _fit_factory(model_kind):
        def fit(data):
            ch, rw = data["choices"], data["rewards"]
            if model_kind == "rw":
                def nll(x):
                    a, b = x; Q = np.zeros(2); ll = 0.0
                    for c, r in zip(ch, rw):
                        m = np.max(b * Q)
                        ll += b * Q[c] - (m + np.log(np.sum(np.exp(b * Q - m))))
                        Q[c] += a * (r - Q[c])
                    return -ll
                bounds = [(1e-4, 1 - 1e-4), (1e-4, 30)]
                x0 = [0.3, 3.0]
                k = 2
            else:
                def nll(x):
                    ap, an, b = x; Q = np.zeros(2); ll = 0.0
                    for c, r in zip(ch, rw):
                        m = np.max(b * Q)
                        ll += b * Q[c] - (m + np.log(np.sum(np.exp(b * Q - m))))
                        pe = r - Q[c]
                        Q[c] += (ap if pe > 0 else an) * pe
                    return -ll
                bounds = [(1e-4, 1 - 1e-4), (1e-4, 1 - 1e-4), (1e-4, 30)]
                x0 = [0.3, 0.3, 3.0]
                k = 3
            best = None
            rng = np.random.default_rng()
            for _ in range(5):
                start = [rng.uniform(lo, hi) for lo, hi in bounds]
                res = minimize(nll, start, method="L-BFGS-B", bounds=bounds)
                if best is None or res.fun < best.fun:
                    best = res
            return {"nll": best.fun, "k": k}
        return fit

    models = {
        "rw":   {"simulate": sim_rw,
                 "fit": _fit_factory("rw"),
                 "param_ranges": {"alpha": (0.05, 0.6), "beta": (1.0, 6.0)},
                 "k": 2},
        "dual": {"simulate": sim_dual,
                 "fit": _fit_factory("dual"),
                 "param_ranges": {"alpha_p": (0.05, 0.6),
                                  "alpha_n": (0.05, 0.6),
                                  "beta": (1.0, 6.0)},
                 "k": 3},
    }

    cm, im = run_model_recovery(models, n_sims=20, n_trials=200, ic="aic")
    print_recovery_matrices(cm, im)
